//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace timesheet_net
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectMembers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjectMembers()
        {
            this.Timesheets = new HashSet<Timesheets>();
        }
    
        public int ProjectMemberID { get; set; }
        public int ProjectID { get; set; }
        public int EmployeeID { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Projects Projects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Timesheets> Timesheets { get; set; }
    }
}
